### ISSUE TITLE
support adding the expose URL to OAuthClient

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/exposecontroller#4]
on OpenShift we need to put the externalUrl of a service into OAuthClients so that the OAuth redirect can go back to the service. e.g. logging in with the fabric8 console.

Right now we've some magic in gofabric8. It'd be nice to be able to run fabric8 on openshift with the minimum possible magic required (e.g. gofabric8). e.g. so that we can install fabric8 via the openshift console itself.

So it'd be nice when `exposecontroller` is running on OpenShift to also watch `OAuthClient` which have the same label (say `expose: true`?) then whenever the service gets annotated, we also check if there's an OAuthClient of the same name with that label, if so we ensure that the externalUrl is inside the list of redirects.

e.g. when using ingress, route or nodePort - its hard at install time to know what the serviceURL is gonna be when the `OAuthClient` gets created. So its cleaner for `exposecontroller` to add the serviceURL when it adds the `exposeUrl `annotation

**Comment by jstrachan** [comment]
here's an example of the fabric8 OAuthClient thats been explicitly updated by gofabric8 on install:
```
apiVersion: v1
kind: OAuthClient
metadata:
  creationTimestamp: null
  name: fabric8
redirectURIs:
- http://localhost:9090
- http://localhost:2772
- http://localhost:9000
- http://fabric8.192.168.64.70.xip.io
- https://fabric8.192.168.64.70.xip.io
- http://192.168.64.70:31448  
```

notice the last entry is the exposeUrl based on nodeport.

Note that moving this logic into `exposecontroller` also helps the system be more dynamic. e.g. a cluster may start using nodePort then later on an ingress could be created for the system - right now the only way to change the fabric8 URL is to re-install  ;)
